[package]
name = "qr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
quircs = "0.10.0"
qrcode-generator = "4.1.2"
image = "0.23.14"